### ISSUE TITLE
create branch for epitkit tutorials

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/varnish#10]
hi @Bisaloo , could you help us create one new branch for the `epitkit` tutorial repository? This repo will host the code and challenges available in the MOOC

The `epitkit` logo is in this comment https://github.com/epiverse-trace/epitkit/issues/6#issuecomment-2419547625

**Comment by Bisaloo** [comment]
https://github.com/epiverse-trace/varnish/tree/epitkit
