### ISSUE TITLE
homogenize logos or make them time-independent

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/varnish#6]
the current epiverse-trace logo only includes the word "epiverse". Should this be updated to "Epiverse-TRACE" as in the epimodelac logo?
https://github.com/epiverse-trace/varnish/blob/epiversetheme/inst/pkgdown/assets/assets/images/epiverse-logo.svg

the current epimodelac logo includes the year "2023". Should we remove the year to make them time-independent?
https://github.com/epiverse-trace/varnish/blob/tracelactheme/inst/pkgdown/assets/assets/images/logo_epimodelac.png

**Comment by Bisaloo** [comment]
Superseded by #10
