### ISSUE TITLE
Get the background of Figure captions

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/varnish#8]
This is to request an update (or fix) to try to get the background of Figure captions

Two examples to compare:
- from template "[Sun arise each and every morning](https://carpentries.github.io/workbench-template-rmd/introduction.html#figures)" (Built with sandpaper (0.16.3), pegboard (0.7.4), and varnish (1.0.1))
- from tutorials "[An overview of the tutorial topics](https://epiverse-trace.github.io/tutorials-middle/#epiverse-trace-tutorials)" (Built with sandpaper (0.16.2), pegboard (0.7.4), and varnish (1.0.1.9000))

@Bisaloo filling this in sandpaper, but do not know whether this belongs to sandpaper or varnish at the moment

**Comment by Bisaloo** [comment]
This is fixed by https://github.com/epiverse-trace/varnish/commit/64bd62470db884f6cb3183becca019f379e4eec1 which is now in our fork & branch. You'll need to re-render lessons to see this change.

e.g., https://epiverse-trace.github.io/tutorials/index.html
